title: Thank You PHP
description: An open letter of gratitude to PHP

defaults:
  - scope:
      path: ""
    values:
      image: thank-you-php.png

plugins:
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules/
  - package-lock.json
  - package.json
  - README.md
  - thank-you-php/
